---
elk_cluster_name: "elk-cluster"
elk_node_name: "node-1"
elasticsearch_heap_size: 1g
logstash_heap_size: 1g


# -------------------------------Bar metal Variable-----------------------------------------------------------
install_bar_metal_elk: true
es_version: "6.2.4"
## Elastic vars
elasticsearch_data_dirs: "/var/lib/elasticsearch"


# Kibana parameters
kibana_version: "{{es_version}}"
kibana_server_port: 5601
kibana_server_host: "0.0.0.0"
kibana_elasticsearch_url: "http://localhost:9200"

#Install search guard plugins
kibana_plugins:
  - plugin: https://search.maven.org/remotecontent?filepath=com/floragunn/search-guard-kibana-plugin/6.2.4-13/search-guard-kibana-plugin-6.2.4-13.zip

## Search guard parameters
kibana_config:
  elasticsearch.username: "kibanaserver"
  elasticsearch.password: "kibanaserver"
  searchguard.basicauth.login.brandimage: http://www.openio.io/wp-content/uploads/2017/02/OIO_LOGO_rgb_red.png
  searchguard.readonly_mode.roles: [ "sg_customer_access" ]
  elasticsearch.ssl.verificationMode: none
  elasticsearch.requestHeadersWhitelist: [ "Authorization", "sgtenant" ]
  searchguard.multitenancy.enable_filter: false
  searchguard.multitenancy.tenants.enable_global: false
  kibana.index: ".kibana"

#--------------------------------------------------Visualisations, dashboards and searches--------------------------------------
# set the variable at true if you want import kibana objects (visualisations, dashboards and searches)
import_kibana_objects: true

kibana_server_group: elkservers
kibana_interface: lo
# location of kibana objects
kibana_dashboard_path: "../files/dashboards/dashboard.json"
kibana_visualization_path: "../files/dashboards/visualization.json"
kibana_search_path: "../files/dashboards/search.json"


kibana_index_pattern: "oio-*"
kibana_time_filter: "@timestamp"

kibana_user: "admin"
kibana_password: "openio10"
...
