---
elk_cluster_name: "elk-cluster"
elk_node_name: "node-1"
elasticsearch_heap_size: 1g
logstash_heap_size: 1g


# -------------------------------Bar metal Variable-----------------------------------------------------------
install_bar_metal_elk: true
es_version: "6.2.4"
## Elastic vars
elasticsearch_data_dirs: "/var/lib/elasticsearch"

## kibana vars
kibana_config:
  elasticsearch.username: "kibanaserver"
  elasticsearch.password: "kibanaserver"
  searchguard.basicauth.login.brandimage: http://www.openio.io/wp-content/uploads/2017/02/OIO_LOGO_rgb_red.png
  searchguard.readonly_mode.roles: ["sg_customer_access"]
  elasticsearch.ssl.verificationMode: none
  elasticsearch.requestHeadersWhitelist: [ "Authorization", "sgtenant" ]
  searchguard.multitenancy.enable_filter: false
  searchguard.multitenancy.tenants.enable_global: false
  kibana.index: ".kibana"





## Kibana Dashboard and visualizations
kibana_server_group: elkservers
kibana_interface: lo
kibana_dashboard_path: "{{ docker_repo_path }}/docker-elkf-{{ docker_elk_version }}/elk/kibana/dashboard/dashboard.json"
kibana_visualization_path: "{{ docker_repo_path }}/docker-elkf-{{ docker_elk_version }}/elk/kibana/dashboard/visualization.json"

kibana_server_ip: "{{ hostvars[groups[kibana_server_group][0]]['ansible_'+ kibana_interface]['ipv4']['address'] }}"
kibana_user: kibanaserver
kibana_password: kibanaserver
...
