sudo: required

services:
  - docker
env:
  matrix:
    - distribution: centos
      version: 7
      init: "/usr/lib/systemd/systemd"
      run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - distribution: ubuntu
      version: 16.04
      run_opts: "--volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - distribution: ubuntu
      version: 18.04
      run_opts: "--volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"


before_install:
  - sudo apt-get update
  - 'docker pull  cdelgehier/docker_images_ansible:2.5_${distribution}_${version}'
  - 'docker run ${run_opts}  --name elk_${version} --volume=${PWD}:/etc/ansible/elk/ cdelgehier/docker_images_ansible:2.5_${distribution}_${version} ${init}'



script:
  # run playbook
  - container_id=$(mktemp)
  - 'docker exec elk_${version} ansible-galaxy install -r requirements.yml --force'
  - 'docker exec elk_${version} ansible-playbook -i inventories/bar-metal/hosts test.yml > ${container_id}'


after_install:
   - 'docker rm -f elk_{version}'
