sudo: required

services:
  - docker
env:
  matrix:
    - distribution: centos
      version: 7
      init: "/usr/lib/systemd/systemd"
      run_opts: "--detach --privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - distribution: ubuntu
      version: 16.04
      run_opts: "--detach --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - distribution: ubuntu
      version: 18.04
      run_opts: "--detach --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"


before_install:
  - sudo apt-get update
  - sudo apt-get install python-jmespath
  - sudo pip install --upgrade pip
  - pip install jmespath
  - 'docker pull  cdelgehier/docker_images_ansible:2.5_${distribution}_${version}'
  - 'docker run ${run_opts}  --name elk_${version} --volume=${PWD}:/etc/ansible/elk/ cdelgehier/docker_images_ansible:2.5_${distribution}_${version} ${init}'



script:
  # run playbook
  - 'docker exec elk_${version} ansible-galaxy install -r /etc/ansible/elk/requirements.yml --force'
  - 'docker exec --tty elk_${version} ansible-playbook -i /etc/ansible/elk/inventories/bar-metal/hosts /etc/ansible/elk/test.yml'


after_install:
   - 'docker rm -f elk_{version}'
