sudo: required

services:
  - docker
env:
  matrix:
    - distribution: centos
      version: 7
      init: "/usr/lib/systemd/systemd"
      run_opts: "--detach --privileged=true --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - distribution: ubuntu
      version: 16.04
      init: "/sbin/init"
      run_opts: "--detach --privileged=true --volume=/run --volume=/run/lock --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro  --cap-add=SYS_ADMIN --cap-add=SYS_RESOURCE"
    - distribution: ubuntu
      version: 18.04
      init: "/sbin/init"
      run_opts: "--detach --privileged=true --volume=/run --volume=/run/lock --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro  --cap-add=SYS_ADMIN --cap-add=SYS_RESOURCE"


before_install:
  - sudo apt-get update
  - 'docker pull  cdelgehier/docker_images_ansible:2.5_${distribution}_${version}'
  - 'docker run ${run_opts}  --name elk_${version} --volume=${PWD}:/etc/ansible/elk/ cdelgehier/docker_images_ansible:2.5_${distribution}_${version} ${init}'
  - 'docker exec elk_${version} pip install jmespath'


script:
  # run playbook
  - 'docker exec elk_${version} ansible-galaxy install -r /etc/ansible/elk/requirements.yml --force'
  - 'docker exec --tty elk_${version} ansible-playbook -i /etc/ansible/elk/inventories/bar-metal/hosts /etc/ansible/elk/test.yml'


after_install:
   - 'docker rm -f elk_{version}'
