sudo: required

services:
  - docker
env:
  matrix:
    - DISTRIBUTION: centos
      VERSION: 7
    - DISTRIBUTION: ubuntu
      VERSION: 16.04


before_install:
    # Install latest Git
  - sudo apt-get update
  - sudo apt-get install --only-upgrade git
    # Allow fetching other branches than master
  - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
    # Fetch the branch with test code
  - git fetch origin docker-tests
  - git worktree add docker-tests origin/docker-tests
  - chmod +X docker-tests/docker-tests.sh

   # Lint
  - sudo pip install --upgrade pip
  - sudo pip install ansible-lint yamllint

  - sudo pip install jmespath

script:


  #Run bar metal mode
  - ./docker-tests/docker-tests.sh && export CONTAINER_ID=$(docker ps -qa | head -n 1)
  - sed -i -e "s@elk_node1 .*@elk_node1 ansible_host=$CONTAINER_ID ansible_user=root ansible_connection=docker@" inventories/bar-metal/hosts


  - ./docker-tests/docker-tests.sh && export CONTAINER_ID=$(docker ps -qa | head -n 1)
  - sed -i -e "s@filebeat_node1 .*@filebeat_node1 ansible_host=$CONTAINER_ID ansible_user=root ansible_connection=docker@" inventories/bar-metal/hosts
  - docker ps
  - docker images
  - ansible-galaxy install -r requirements.yml --force
  - ansible-playbook -i inventories/bar-metal/hosts main.yml

after_install:
  - docker rm -f $(docker ps -aq)
