sudo: required

services:
  - docker
env:
  matrix:
    - DISTRIBUTION: centos
      VERSION: 7
    - DISTRIBUTION: ubuntu
      VERSION: 16.04


before_install:
    # Install latest Git
  - sudo apt-get update
  - sudo apt-get install --only-upgrade git
    # Allow fetching other branches than master
  - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
    # Fetch the branch with test code
  - git fetch origin docker-tests
  - git worktree add docker-tests origin/docker-tests
  - chmod +X docker-tests/docker-tests.sh

   # Lint
  - sudo pip install --upgrade pip
  - sudo pip install ansible-lint yamllint

  - sudo pip install jmespath

script:
  # Lint
  - ansible-lint . -x ANSIBLE0016
  - yamllint .
  # Run docker elk
  - ./docker-tests/docker-tests.sh && export FILEBEAT_CONTAINER_ID=$(docker ps -qa | head -n 1)
  - sed -i -e "s@filebeat_node1 .*@filebeat_node1 ansible_host=$FILEBEAT_CONTAINER_ID ansible_user=root ansible_connection=docker@" inventories/docker/hosts

  - ansible-galaxy install -r requirements.yml --force
  - ansible-playbook -i inventories/docker/hosts main.yml

  - export ELK_CONTAINER_ID_1=$(docker ps -qa | head -n 1)
  #Run bar metal mode
  - ./docker-tests/docker-tests.sh && export ELK_CONTAINER_ID_2=$(docker ps -qa | head -n 1)
  - sed -i -e "s@elk_node1 .*@elk_node1 ansible_host=$ELK_CONTAINER_ID_2 ansible_user=root ansible_connection=docker@" inventories/bar-metal/hosts


  - ./docker-tests/docker-tests.sh && export FILEBEAT_CONTAINER_ID=$(docker ps -qa | head -n 1)
  - sed -i -e "s@filebeat_node1 .*@filebeat_node1 ansible_host=$FILEBEAT_CONTAINER_ID ansible_user=root ansible_connection=docker@" inventories/bar-metal/hosts

  - ansible-playbook -i inventories/bar-metal/hosts main.yml


  # Run functional tests on the container (docker mode )
  - CONTAINER_ID=${ELK_CONTAINER_ID_1} ACCESS=admin:openio10 ./docker-tests/functional-tests.sh

  # Run functional tests on the container (bar-metal mode )
  - CONTAINER_IP=172.17.0.3 ACCESS=admin:openio10 ./docker-tests/functional-tests.sh



after_install:
  - docker rm -f $(docker ps -aq)
