---

- hosts: elkservers
  remote_user: openio
  become: true
  vars:
    elk_git_repository: /home/openio/loganalyzer
    elk_git_url: https://github.com/papebadiane/docker-elkf
  roles:
    - role: docker
      docker_install_compose: true
      docker_compose_version: 1.18.0
      docker_apt_repository: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      docker_compose_path: /usr/bin/docker-compose
  tasks:
  - name: Increase the virtual memory
    shell: sysctl -w vm.max_map_count=262144

  - name: Clone github repository
    git:
      repo: '{{ elk_git_url }}'
      dest: '{{ elk_git_repository }}'
      clone: yes

  # - name: change the working directory {{ elk_git_repository }} and run the container ELK
  #   shell: docker-compose up --build elk
  #   args:
  #     chdir: '{{ elk_git_repository }}'
