---
- hosts: filebeatservers
  become: yes
  environment:
    http_proxy: http://172.16.140.4:3128
    https_proxy: http://172.16.140.4:3128
  roles:
    - geerlingguy.filebeat
      filebeat_prospectors:
        - type: log
          enabled: true
          paths:
            - /var/log/oio/sds/SCALAIR/oioswift-*/oioswift-*.log
          fields:
            name_log: oio-swift
        - type: log
          enabled: true
          paths:
            - /var/log/oio/sds/SCALAIR/*/*.access
            - /var/log/oio/sds/SCALAIR/rawx-*/*-access.log
          fields:
            name_log: oio-access
        - type: log
          enabled: true
          paths:
            - /var/log/oio/sds/SCALAIR/meta*/*.log
            - /var/log/oio/sds/SCALAIR/conscience*/*.log
            - /var/log/oio/sds/SCALAIR/oioproxy-*/*.log
            - /var/log/oio/sds/SCALAIR/oio-event-agent*/*.log
          fields:
            name_log: oio-logs
        # - type: log
        #   enabled: true
        #   paths:
        #     - /var/log/oio/sds/SCALAIR/oio-blob-indexer-*/*.log
        #   fields:
        #     name_log: oio-blob-indexer
        # - type: log
        #   enabled: true
        #   paths:
        #     - /var/log/oio/sds/SCALAIR/account-*/*.log
        #   fields:
        #     name_log: oio-account
        # - type: log
        #   enabled: true
        #   paths:
        #     - /var/log/oio/sds/SCALAIR/redis-*/*.log
        #   fields:
        #     name_log: oio-redis
        # - type: log
        #   enabled: true
        #   paths:
        #     - /var/log/oio/sds/SCALAIR/*/*-errors.log
        #   fields:
        #     name_log: oio-errors
      filebeat_output_logstash_hosts:
        - "163.172.72.26:5044"
      filebeat_ssl_dir: /etc/pki/logstash
      filebeat_ssl_certificate_file: ""
