---
- hosts: filebeatservers
  become: yes
  roles:
    - role: filebeat
      filebeat_prospectors:
        - input_type: log
          paths:
            - /var/log/oio/sds/OPENIO/oioswift-*/oioswift-*.log
          fields:
            name_log: oio-swift

        - input_type: log
          paths:
            - /var/log/oio/sds/OPENIO/*/*.access
            - /var/log/oio/sds/OPENIO/rawx-0/rawx-0-httpd-access.log
          fields:
            name_log: access-oio
        - input_type: log
          paths:
            - /var/log/oio/sds/OPENIO/meta*/*.log
            - /var/log/oio/sds/OPENIO/conscience*/*.log
            - /var/log/oio/sds/OPENIO/oio*/*.log
          fields:
            name_log: logs-oio
      filebeat_output_logstash_hosts:
        - "185.75.141.10:5044"
      filebeat_ssl_dir: /etc/pki/logstash
      filebeat_ssl_certificate_file: ""
