---
- hosts: localhost
  connection: local
  remote_user: root
  tasks:
    - debug:
    - name: Add the GPG key
      command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

    #- name: Add the Docker repository
    - apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
        state: present

    - name: Run apt-get update
      apt:
        update_cache: true

    - name: Install Docker
      apt:
        name: docker-ce
        update_cache: true


    - name: Add user "pape" to sudo group
      command: usermod -aG docker pape

    - name: test docker
      command: docker --version

    - name: Install Docker compose
      command: curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose

    - name: set docker-compose permissions
      command: chmod +x /usr/local/bin/docker-compose

    - name: test docker compose
      command: docker-compose --version
    #
    # - name: Clone github repository
    #
    # - name: change WORKDIR
    #   command:
    #   notify: "The workdir is channing"
    #
    # - name: Run container
    #   command: usermod -aG docker ${USER}
    #   notify: "The container is running"
