---
- src: https://github.com/geerlingguy/ansible-role-java
  version: 1.8.1
- src: https://github.com/geerlingguy/ansible-role-filebeat
  version: 1.3.0
- src: https://github.com/geerlingguy/ansible-role-docker
  version: 2.1.0
- src: https://github.com/papebadiane/ansible-role-kibana-import-dashboard-and-visualization
  version: 0.1.2
- src: https://github.com/elastic/ansible-elasticsearch
  version: 6.3.1
...
