---

 - name: ensure repository key is installed
   apt_key:
     url: 'https://download.docker.com/linux/ubuntu/gpg'
     id: '9DC858229FC7DD38854AE2D88D81803C0EBFCD88'
     state: 'present'

 - name: Add the Docker repository
   apt_repository:
     repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
     state: present
     update_cache: True

 - name: Run apt-get update
   apt:
     update_cache: true

 - name: Install Docker
   apt:
     name: docker-ce
     update_cache: true

 - name: Install Git
   apt:
     name: git
     update_cache: true

 - name: 'add users to docker group'
   user:
    name: '{{ item }}'
    groups: 'docker'
    append: 'yes'
   with_items: '{{ docker_group_members }}'
   when: 'docker_group_members is defined'


 - name: Install Docker compose
   get_url:
     url : https://github.com/docker/compose/releases/download/1.18.0/docker-compose-Linux-x86_64
     dest: /usr/local/bin/docker-compose


   - name: set docker-compose permissions
     file:
       path: /usr/local/bin/docker-compose
       mode: "+x"

 - name: Clone github repository
   git:
     repo: '{{ elk_git_url }}'
     dest: '{{ elk_git_repository }}'
     clone: yes
