---
elk_cluster_name: "elk-cluster"
elk_node_name: "node-1"
elasticsearch_heap_size: 1g
logstash_heap_size: 1g


#-------------------------------------- Docker container Variable------------------------------------------
install_docker_elk: truue
docker_elk_version: "0.1.4"
docker_repo_path: "/var/lib/loganalyzer"



##--------------------- Kibana Dashboard and visualizations------------------------------------------------
kibana_server_group: elkservers
kibana_interface: lo
kibana_dashboard_path: "{{ docker_repo_path }}/docker-elkf-{{ docker_elk_version }}/elk/kibana/dashboard/dashboard.json"
kibana_visualization_path: "{{ docker_repo_path }}/docker-elkf-{{ docker_elk_version }}/elk/kibana/dashboard/visualization.json"

kibana_server_ip: "{{ hostvars[groups[kibana_server_group][0]]['ansible_'+ kibana_interface]['ipv4']['address'] }}"
kibana_user: kibanaserver
kibana_password: kibanaserver
...
