---

elk_cluster_name: "elk-cluster"
elk_node_name: "node-1"
elasticsearch_heap_size: 2g
logstash_heap_size: 1g


#-------------------------------------- Docker container Variable------------------------------------------
install_docker_elk: true
docker_elk_version: "0.1.4"
docker_repo_path: "/var/lib/loganalyzer"


#--------------------------------------------------Visualisations, dashboards and searches--------------------------------------
# set the variable at true if you want import kibana objects (visualisations, dashboards and searches)
import_kibana_objects: true

kibana_server_group: elkservers
kibana_interface: lo
# location of kibana objects
kibana_dashboard_path: "{{docker_repo_path}}/oio-elk-{{ docker_elk_version }}/elk/kibana/dashboard/dashboard.json"
kibana_visualization_path: "{{docker_repo_path}}/oio-elk-{{ docker_elk_version }}/elk/kibana/dashboard/visualization.json"
kibana_search_path: "{{docker_repo_path}}/oio-elk-{{ docker_elk_version }}/elk/kibana/dashboard/search.json"

kibana_dashboard: "{{ lookup('file', '../../../files/dashboards/dashboard.json') | from_json }}"
kibana_visualization: "{{ lookup('file', '../../../files/dashboards/visualization.json') | from_json }}"
kibana_search: "{{ lookup('file', '../../../files/dashboards/search.json') | from_json }}"

kibana_index_pattern: "oio-*"
kibana_time_filter: "@timestamp"

kibana_user: "admin"
kibana_password: "openio10"
...
