---

- hosts: elkservers
  become: true
  environment:
    ES_HEAP_SIZE: "{{ elasticsearch_heap_size }}"
    LS_HEAP_SIZE: "{{ logstash_heap_size }}"
    ES_CLUSTER_NAME: "{{ elk_cluster_name }}"
  vars:
      elk_install_path: "{{ docker_repo_path }}"
      elk_repo_version: "{{ docker_elk_version }}"
  roles:
    - role: ansible-role-java

    - role: ansible-role-docker
      docker_install_compose: true
      docker_compose_version: "1.18.0"
      docker_apt_repository: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
      docker_compose_path: "/usr/bin/docker-compose"
  tasks:
    - name: Increase the virtual memory
      shell: sysctl -w vm.max_map_count=262144

    - name: Creates directory
      file:
        path: "{{ elk_install_path }}"
        state: directory
    - name: Download elk
      unarchive:
        src: "https://github.com/papebadiane/docker-e=lkf/archive/{{ elk_repo_version}}.tar.gz"
        dest: "{{ elk_install_path }}"
        remote_src: true

    - name: "change the working directory {{ elk_install_path }}/docker-elkf-{{ elk_repo_version }} and run the container ELK"
      shell: docker-compose up -d --build elk
      args:
        chdir: "{{ elk_install_path }}/docker-elkf-{{ elk_repo_version }}"

...
