---
- name: Kibana with custom configuration"
  hosts: elkservers
  become: true
  roles:
    - role: ansible-role-kibana
  vars:
    kibana_version: "{{es_version}}"
    kibana_server_port: 5601
    kibana_server_host: "0.0.0.0"
    kibana_elasticsearch_url: "http://localhost:9200"
    kibana_plugins:
      - plugin: https://search.maven.org/remotecontent?filepath=com/floragunn/search-guard-kibana-plugin/6.2.4-13/search-guard-kibana-plugin-6.2.4-13.zip
...
