---
- name: logstash with custom configuration"
  hosts: elkservers
  become: true
  roles:
    - role: ansible-role-logstash
  vars:
    logstash_version: "{{es_version}}"
    logstash_enabled_on_boot: false

...
